version: "3"
services:

  mysql:
    image: chrispynegar/mysql
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
  
  workspace:
    image: chrispynegar/laravel-php-nginx
    ports:
      - 80:80
    volumes:
      - ./:/app

volumes:
  db_data:
